app:
    build: .
    environment:
        REALM: prod
        REDIS_URL: "//redis:6379"
    links:
        - redis
    ports:
        - "8000:8000"

redis:
    image: redis

ngrok:
    image: wernight/ngrok
    ports:
        - 4040:4040
    links:
        - app
    environment:
        NGROK_PORT: 'app:8000'
